server:
  port: 8002
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer_route
          uri: lb://GATEWAY-SERVICE
          predicates:
            - Path= /api/**
            - Method=GET
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1 #令牌桶每秒填充速率
                redis-rate-limiter.burstCapacity: 2 #令牌桶总容量
                key-resolver: "#{@remoteAddrKeyResolver}" #bean对象的名字，从spring容器中获取
 redis:
    host: 127.0.0.1
    port: 6379
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka/

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug
feign:
  hystrix:
    enabled: true
hystrix:
 command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
