server:
  port: 8010
spring:
  application:
    name: eureka-consumer
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://peer1:1111/eureka/
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 3
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            interruptOnTimeOut: true
            timeoutInMilliseconds: 5000
